
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.vapeaholic.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.vapeaholic.item.YellowWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.YellowVapeItem;
import net.mcreator.vapeaholic.item.YellowSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.YellowSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.YellowNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.YellowJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.YellowInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.YellowFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteVapeItem;
import net.mcreator.vapeaholic.item.WhiteSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.WhiteFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.WaterFilledVapePodItem;
import net.mcreator.vapeaholic.item.VapePodOfWaterBreathingItem;
import net.mcreator.vapeaholic.item.VapePodOfTheTurtleMasterItem;
import net.mcreator.vapeaholic.item.VapePodOfSwiftnessItem;
import net.mcreator.vapeaholic.item.VapePodOfSlownessItem;
import net.mcreator.vapeaholic.item.VapePodOfNightVisionItem;
import net.mcreator.vapeaholic.item.VapePodOfJumpBoostItem;
import net.mcreator.vapeaholic.item.VapePodOfInvisibilityItem;
import net.mcreator.vapeaholic.item.VapePodOfFireResistanceItem;
import net.mcreator.vapeaholic.item.ThickPotionFilledVapePodItem;
import net.mcreator.vapeaholic.item.RedWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.RedVapeItem;
import net.mcreator.vapeaholic.item.RedSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.RedSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.RedNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.RedJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.RedInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.RedFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleVapeItem;
import net.mcreator.vapeaholic.item.PurpleSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.PurpleFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkVapeItem;
import net.mcreator.vapeaholic.item.PinkSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.PinkFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeVapeItem;
import net.mcreator.vapeaholic.item.OrangeSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.OrangeFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.MundanePotionFilledVapePodItem;
import net.mcreator.vapeaholic.item.MouthpieceItem;
import net.mcreator.vapeaholic.item.MagentaWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.MagentaVapeItem;
import net.mcreator.vapeaholic.item.MagentaSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.MagentaSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.MagentaNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.MagentaJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.MagentaInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.MagentaFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeVapeItem;
import net.mcreator.vapeaholic.item.LimeSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.LimeFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGrayWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGrayVapeItem;
import net.mcreator.vapeaholic.item.LightGraySwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGraySlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGrayNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGrayJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGrayInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.LightGrayFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueVapeItem;
import net.mcreator.vapeaholic.item.LightBlueSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.LightBlueFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenVapeItem;
import net.mcreator.vapeaholic.item.GreenSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.GreenFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.GrayWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.GraySwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.GraySlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.GrayNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.GrayJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.GrayItem;
import net.mcreator.vapeaholic.item.GrayInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.GrayFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.EmptyVapePodItem;
import net.mcreator.vapeaholic.item.CyanWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.CyanVapeItem;
import net.mcreator.vapeaholic.item.CyanSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.CyanSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.CyanNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.CyanJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.CyanInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.CyanFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.CoilItem;
import net.mcreator.vapeaholic.item.BrownWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.BrownVapeItem;
import net.mcreator.vapeaholic.item.BrownSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.BrownSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.BrownNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.BrownJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.BrownInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.BrownFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueVapeItem;
import net.mcreator.vapeaholic.item.BlueSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.BlueFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackWaterFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackVapeItem;
import net.mcreator.vapeaholic.item.BlackSwiftnessFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackSlownessFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackNightVisionFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackJumpBoostFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackInvisibilityFilledVapeItem;
import net.mcreator.vapeaholic.item.BlackFireResistanceFilledVapeItem;
import net.mcreator.vapeaholic.item.BatteryItem;
import net.mcreator.vapeaholic.item.AwkwardPotionFilledVapePodItem;
import net.mcreator.vapeaholic.VapeaholicMod;

public class VapeaholicModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, VapeaholicMod.MODID);
	public static final RegistryObject<Item> EMPTY_VAPE_POD = REGISTRY.register("empty_vape_pod", () -> new EmptyVapePodItem());
	public static final RegistryObject<Item> WATER_FILLED_VAPE_POD = REGISTRY.register("water_filled_vape_pod", () -> new WaterFilledVapePodItem());
	public static final RegistryObject<Item> MUNDANE_POTION_FILLED_VAPE_POD = REGISTRY.register("mundane_potion_filled_vape_pod", () -> new MundanePotionFilledVapePodItem());
	public static final RegistryObject<Item> THICK_POTION_FILLED_VAPE_POD = REGISTRY.register("thick_potion_filled_vape_pod", () -> new ThickPotionFilledVapePodItem());
	public static final RegistryObject<Item> AWKWARD_POTION_FILLED_VAPE_POD = REGISTRY.register("awkward_potion_filled_vape_pod", () -> new AwkwardPotionFilledVapePodItem());
	public static final RegistryObject<Item> VAPE_POD_OF_NIGHT_VISION = REGISTRY.register("vape_pod_of_night_vision", () -> new VapePodOfNightVisionItem());
	public static final RegistryObject<Item> VAPE_POD_OF_INVISIBILITY = REGISTRY.register("vape_pod_of_invisibility", () -> new VapePodOfInvisibilityItem());
	public static final RegistryObject<Item> VAPE_POD_OF_JUMP_BOOST = REGISTRY.register("vape_pod_of_jump_boost", () -> new VapePodOfJumpBoostItem());
	public static final RegistryObject<Item> VAPE_POD_OF_FIRE_RESISTANCE = REGISTRY.register("vape_pod_of_fire_resistance", () -> new VapePodOfFireResistanceItem());
	public static final RegistryObject<Item> VAPE_POD_OF_SWIFTNESS = REGISTRY.register("vape_pod_of_swiftness", () -> new VapePodOfSwiftnessItem());
	public static final RegistryObject<Item> VAPE_POD_OF_SLOWNESS = REGISTRY.register("vape_pod_of_slowness", () -> new VapePodOfSlownessItem());
	public static final RegistryObject<Item> VAPE_POD_OF_THE_TURTLE_MASTER = REGISTRY.register("vape_pod_of_the_turtle_master", () -> new VapePodOfTheTurtleMasterItem());
	public static final RegistryObject<Item> WHITE_VAPE = REGISTRY.register("white_vape", () -> new WhiteVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_VAPE = REGISTRY.register("light_gray_vape", () -> new LightGrayVapeItem());
	public static final RegistryObject<Item> GRAYVAPE = REGISTRY.register("grayvape", () -> new GrayItem());
	public static final RegistryObject<Item> BLACK_VAPE = REGISTRY.register("black_vape", () -> new BlackVapeItem());
	public static final RegistryObject<Item> BROWN_VAPE = REGISTRY.register("brown_vape", () -> new BrownVapeItem());
	public static final RegistryObject<Item> RED_VAPE = REGISTRY.register("red_vape", () -> new RedVapeItem());
	public static final RegistryObject<Item> ORANGE_VAPE = REGISTRY.register("orange_vape", () -> new OrangeVapeItem());
	public static final RegistryObject<Item> YELLOW_VAPE = REGISTRY.register("yellow_vape", () -> new YellowVapeItem());
	public static final RegistryObject<Item> LIME_VAPE = REGISTRY.register("lime_vape", () -> new LimeVapeItem());
	public static final RegistryObject<Item> GREEN_VAPE = REGISTRY.register("green_vape", () -> new GreenVapeItem());
	public static final RegistryObject<Item> CYAN_VAPE = REGISTRY.register("cyan_vape", () -> new CyanVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_VAPE = REGISTRY.register("light_blue_vape", () -> new LightBlueVapeItem());
	public static final RegistryObject<Item> BLUE_VAPE = REGISTRY.register("blue_vape", () -> new BlueVapeItem());
	public static final RegistryObject<Item> PURPLE_VAPE = REGISTRY.register("purple_vape", () -> new PurpleVapeItem());
	public static final RegistryObject<Item> MAGENTA_VAPE = REGISTRY.register("magenta_vape", () -> new MagentaVapeItem());
	public static final RegistryObject<Item> PINK_VAPE = REGISTRY.register("pink_vape", () -> new PinkVapeItem());
	public static final RegistryObject<Item> WHITE_WATER_FILLED_VAPE = REGISTRY.register("white_water_filled_vape", () -> new WhiteWaterFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_WATER_FILLED_VAPE = REGISTRY.register("light_gray_water_filled_vape", () -> new LightGrayWaterFilledVapeItem());
	public static final RegistryObject<Item> GRAY_WATER_FILLED_VAPE = REGISTRY.register("gray_water_filled_vape", () -> new GrayWaterFilledVapeItem());
	public static final RegistryObject<Item> BLACK_WATER_FILLED_VAPE = REGISTRY.register("black_water_filled_vape", () -> new BlackWaterFilledVapeItem());
	public static final RegistryObject<Item> BROWN_WATER_FILLED_VAPE = REGISTRY.register("brown_water_filled_vape", () -> new BrownWaterFilledVapeItem());
	public static final RegistryObject<Item> RED_WATER_FILLED_VAPE = REGISTRY.register("red_water_filled_vape", () -> new RedWaterFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_WATER_FILLED_VAPE = REGISTRY.register("orange_water_filled_vape", () -> new OrangeWaterFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_WATER_FILLED_VAPE = REGISTRY.register("yellow_water_filled_vape", () -> new YellowWaterFilledVapeItem());
	public static final RegistryObject<Item> LIME_WATER_FILLED_VAPE = REGISTRY.register("lime_water_filled_vape", () -> new LimeWaterFilledVapeItem());
	public static final RegistryObject<Item> GREEN_WATER_FILLED_VAPE = REGISTRY.register("green_water_filled_vape", () -> new GreenWaterFilledVapeItem());
	public static final RegistryObject<Item> CYAN_WATER_FILLED_VAPE = REGISTRY.register("cyan_water_filled_vape", () -> new CyanWaterFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_WATER_FILLED_VAPE = REGISTRY.register("light_blue_water_filled_vape", () -> new LightBlueWaterFilledVapeItem());
	public static final RegistryObject<Item> BLUE_WATER_FILLED_VAPE = REGISTRY.register("blue_water_filled_vape", () -> new BlueWaterFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_WATER_FILLED_VAPE = REGISTRY.register("purple_water_filled_vape", () -> new PurpleWaterFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_WATER_FILLED_VAPE = REGISTRY.register("magenta_water_filled_vape", () -> new MagentaWaterFilledVapeItem());
	public static final RegistryObject<Item> PINK_WATER_FILLED_VAPE = REGISTRY.register("pink_water_filled_vape", () -> new PinkWaterFilledVapeItem());
	public static final RegistryObject<Item> WHITE_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("white_night_vision_filled_vape", () -> new WhiteNightVisionFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("light_gray_night_vision_filled_vape", () -> new LightGrayNightVisionFilledVapeItem());
	public static final RegistryObject<Item> GRAY_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("gray_night_vision_filled_vape", () -> new GrayNightVisionFilledVapeItem());
	public static final RegistryObject<Item> BLACK_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("black_night_vision_filled_vape", () -> new BlackNightVisionFilledVapeItem());
	public static final RegistryObject<Item> BROWN_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("brown_night_vision_filled_vape", () -> new BrownNightVisionFilledVapeItem());
	public static final RegistryObject<Item> RED_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("red_night_vision_filled_vape", () -> new RedNightVisionFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("orange_night_vision_filled_vape", () -> new OrangeNightVisionFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("yellow_night_vision_filled_vape", () -> new YellowNightVisionFilledVapeItem());
	public static final RegistryObject<Item> LIME_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("lime_night_vision_filled_vape", () -> new LimeNightVisionFilledVapeItem());
	public static final RegistryObject<Item> GREEN_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("green_night_vision_filled_vape", () -> new GreenNightVisionFilledVapeItem());
	public static final RegistryObject<Item> CYAN_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("cyan_night_vision_filled_vape", () -> new CyanNightVisionFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("light_blue_night_vision_filled_vape", () -> new LightBlueNightVisionFilledVapeItem());
	public static final RegistryObject<Item> BLUE_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("blue_night_vision_filled_vape", () -> new BlueNightVisionFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("purple_night_vision_filled_vape", () -> new PurpleNightVisionFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("magenta_night_vision_filled_vape", () -> new MagentaNightVisionFilledVapeItem());
	public static final RegistryObject<Item> PINK_NIGHT_VISION_FILLED_VAPE = REGISTRY.register("pink_night_vision_filled_vape", () -> new PinkNightVisionFilledVapeItem());
	public static final RegistryObject<Item> WHITE_INVISIBILITY_FILLED_VAPE = REGISTRY.register("white_invisibility_filled_vape", () -> new WhiteInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_INVISIBILITY_FILLED_VAPE = REGISTRY.register("light_gray_invisibility_filled_vape", () -> new LightGrayInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> GRAY_INVISIBILITY_FILLED_VAPE = REGISTRY.register("gray_invisibility_filled_vape", () -> new GrayInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> BLACK_INVISIBILITY_FILLED_VAPE = REGISTRY.register("black_invisibility_filled_vape", () -> new BlackInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> BROWN_INVISIBILITY_FILLED_VAPE = REGISTRY.register("brown_invisibility_filled_vape", () -> new BrownInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> RED_INVISIBILITY_FILLED_VAPE = REGISTRY.register("red_invisibility_filled_vape", () -> new RedInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_INVISIBILITY_FILLED_VAPE = REGISTRY.register("orange_invisibility_filled_vape", () -> new OrangeInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_INVISIBILITY_FILLED_VAPE = REGISTRY.register("yellow_invisibility_filled_vape", () -> new YellowInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> LIME_INVISIBILITY_FILLED_VAPE = REGISTRY.register("lime_invisibility_filled_vape", () -> new LimeInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> GREEN_INVISIBILITY_FILLED_VAPE = REGISTRY.register("green_invisibility_filled_vape", () -> new GreenInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> CYAN_INVISIBILITY_FILLED_VAPE = REGISTRY.register("cyan_invisibility_filled_vape", () -> new CyanInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_INVISIBILITY_FILLED_VAPE = REGISTRY.register("light_blue_invisibility_filled_vape", () -> new LightBlueInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> BLUE_INVISIBILITY_FILLED_VAPE = REGISTRY.register("blue_invisibility_filled_vape", () -> new BlueInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_INVISIBILITY_FILLED_VAPE = REGISTRY.register("purple_invisibility_filled_vape", () -> new PurpleInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_INVISIBILITY_FILLED_VAPE = REGISTRY.register("magenta_invisibility_filled_vape", () -> new MagentaInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> PINK_INVISIBILITY_FILLED_VAPE = REGISTRY.register("pink_invisibility_filled_vape", () -> new PinkInvisibilityFilledVapeItem());
	public static final RegistryObject<Item> WHITE_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("white_jump_boost_filled_vape", () -> new WhiteJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("light_gray_jump_boost_filled_vape", () -> new LightGrayJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> GRAY_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("gray_jump_boost_filled_vape", () -> new GrayJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> BLACK_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("black_jump_boost_filled_vape", () -> new BlackJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> BROWN_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("brown_jump_boost_filled_vape", () -> new BrownJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> RED_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("red_jump_boost_filled_vape", () -> new RedJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("orange_jump_boost_filled_vape", () -> new OrangeJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("yellow_jump_boost_filled_vape", () -> new YellowJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> LIME_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("lime_jump_boost_filled_vape", () -> new LimeJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> GREEN_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("green_jump_boost_filled_vape", () -> new GreenJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> CYAN_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("cyan_jump_boost_filled_vape", () -> new CyanJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("light_blue_jump_boost_filled_vape", () -> new LightBlueJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> BLUE_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("blue_jump_boost_filled_vape", () -> new BlueJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("purple_jump_boost_filled_vape", () -> new PurpleJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("magenta_jump_boost_filled_vape", () -> new MagentaJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> PINK_JUMP_BOOST_FILLED_VAPE = REGISTRY.register("pink_jump_boost_filled_vape", () -> new PinkJumpBoostFilledVapeItem());
	public static final RegistryObject<Item> WHITE_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("white_fire_resistance_filled_vape", () -> new WhiteFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("light_gray_fire_resistance_filled_vape", () -> new LightGrayFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> GRAY_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("gray_fire_resistance_filled_vape", () -> new GrayFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> BLACK_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("black_fire_resistance_filled_vape", () -> new BlackFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> BROWN_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("brown_fire_resistance_filled_vape", () -> new BrownFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> RED_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("red_fire_resistance_filled_vape", () -> new RedFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("orange_fire_resistance_filled_vape", () -> new OrangeFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("yellow_fire_resistance_filled_vape", () -> new YellowFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> LIME_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("lime_fire_resistance_filled_vape", () -> new LimeFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> GREEN_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("green_fire_resistance_filled_vape", () -> new GreenFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> CYAN_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("cyan_fire_resistance_filled_vape", () -> new CyanFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("light_blue_fire_resistance_filled_vape", () -> new LightBlueFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> BLUE_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("blue_fire_resistance_filled_vape", () -> new BlueFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("purple_fire_resistance_filled_vape", () -> new PurpleFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("magenta_fire_resistance_filled_vape", () -> new MagentaFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> PINK_FIRE_RESISTANCE_FILLED_VAPE = REGISTRY.register("pink_fire_resistance_filled_vape", () -> new PinkFireResistanceFilledVapeItem());
	public static final RegistryObject<Item> WHITE_SWIFTNESS_FILLED_VAPE = REGISTRY.register("white_swiftness_filled_vape", () -> new WhiteSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_SWIFTNESS_FILLED_VAPE = REGISTRY.register("light_gray_swiftness_filled_vape", () -> new LightGraySwiftnessFilledVapeItem());
	public static final RegistryObject<Item> GRAY_SWIFTNESS_FILLED_VAPE = REGISTRY.register("gray_swiftness_filled_vape", () -> new GraySwiftnessFilledVapeItem());
	public static final RegistryObject<Item> BLACK_SWIFTNESS_FILLED_VAPE = REGISTRY.register("black_swiftness_filled_vape", () -> new BlackSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> BROWN_SWIFTNESS_FILLED_VAPE = REGISTRY.register("brown_swiftness_filled_vape", () -> new BrownSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> RED_SWIFTNESS_FILLED_VAPE = REGISTRY.register("red_swiftness_filled_vape", () -> new RedSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_SWIFTNESS_FILLED_VAPE = REGISTRY.register("orange_swiftness_filled_vape", () -> new OrangeSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_SWIFTNESS_FILLED_VAPE = REGISTRY.register("yellow_swiftness_filled_vape", () -> new YellowSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> LIME_SWIFTNESS_FILLED_VAPE = REGISTRY.register("lime_swiftness_filled_vape", () -> new LimeSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> GREEN_SWIFTNESS_FILLED_VAPE = REGISTRY.register("green_swiftness_filled_vape", () -> new GreenSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> CYAN_SWIFTNESS_FILLED_VAPE = REGISTRY.register("cyan_swiftness_filled_vape", () -> new CyanSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_SWIFTNESS_FILLED_VAPE = REGISTRY.register("light_blue_swiftness_filled_vape", () -> new LightBlueSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> BLUE_SWIFTNESS_FILLED_VAPE = REGISTRY.register("blue_swiftness_filled_vape", () -> new BlueSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_SWIFTNESS_FILLED_VAPE = REGISTRY.register("purple_swiftness_filled_vape", () -> new PurpleSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_SWIFTNESS_FILLED_VAPE = REGISTRY.register("magenta_swiftness_filled_vape", () -> new MagentaSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> PINK_SWIFTNESS_FILLED_VAPE = REGISTRY.register("pink_swiftness_filled_vape", () -> new PinkSwiftnessFilledVapeItem());
	public static final RegistryObject<Item> WHITE_SLOWNESS_FILLED_VAPE = REGISTRY.register("white_slowness_filled_vape", () -> new WhiteSlownessFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_GRAY_SLOWNESS_FILLED_VAPE = REGISTRY.register("light_gray_slowness_filled_vape", () -> new LightGraySlownessFilledVapeItem());
	public static final RegistryObject<Item> GRAY_SLOWNESS_FILLED_VAPE = REGISTRY.register("gray_slowness_filled_vape", () -> new GraySlownessFilledVapeItem());
	public static final RegistryObject<Item> BLACK_SLOWNESS_FILLED_VAPE = REGISTRY.register("black_slowness_filled_vape", () -> new BlackSlownessFilledVapeItem());
	public static final RegistryObject<Item> BROWN_SLOWNESS_FILLED_VAPE = REGISTRY.register("brown_slowness_filled_vape", () -> new BrownSlownessFilledVapeItem());
	public static final RegistryObject<Item> RED_SLOWNESS_FILLED_VAPE = REGISTRY.register("red_slowness_filled_vape", () -> new RedSlownessFilledVapeItem());
	public static final RegistryObject<Item> ORANGE_SLOWNESS_FILLED_VAPE = REGISTRY.register("orange_slowness_filled_vape", () -> new OrangeSlownessFilledVapeItem());
	public static final RegistryObject<Item> YELLOW_SLOWNESS_FILLED_VAPE = REGISTRY.register("yellow_slowness_filled_vape", () -> new YellowSlownessFilledVapeItem());
	public static final RegistryObject<Item> LIME_SLOWNESS_FILLED_VAPE = REGISTRY.register("lime_slowness_filled_vape", () -> new LimeSlownessFilledVapeItem());
	public static final RegistryObject<Item> GREEN_SLOWNESS_FILLED_VAPE = REGISTRY.register("green_slowness_filled_vape", () -> new GreenSlownessFilledVapeItem());
	public static final RegistryObject<Item> CYAN_SLOWNESS_FILLED_VAPE = REGISTRY.register("cyan_slowness_filled_vape", () -> new CyanSlownessFilledVapeItem());
	public static final RegistryObject<Item> LIGHT_BLUE_SLOWNESS_FILLED_VAPE = REGISTRY.register("light_blue_slowness_filled_vape", () -> new LightBlueSlownessFilledVapeItem());
	public static final RegistryObject<Item> BLUE_SLOWNESS_FILLED_VAPE = REGISTRY.register("blue_slowness_filled_vape", () -> new BlueSlownessFilledVapeItem());
	public static final RegistryObject<Item> PURPLE_SLOWNESS_FILLED_VAPE = REGISTRY.register("purple_slowness_filled_vape", () -> new PurpleSlownessFilledVapeItem());
	public static final RegistryObject<Item> MAGENTA_SLOWNESS_FILLED_VAPE = REGISTRY.register("magenta_slowness_filled_vape", () -> new MagentaSlownessFilledVapeItem());
	public static final RegistryObject<Item> PINK_SLOWNESS_FILLED_VAPE = REGISTRY.register("pink_slowness_filled_vape", () -> new PinkSlownessFilledVapeItem());
	public static final RegistryObject<Item> BATTERY = REGISTRY.register("battery", () -> new BatteryItem());
	public static final RegistryObject<Item> COIL = REGISTRY.register("coil", () -> new CoilItem());
	public static final RegistryObject<Item> MOUTHPIECE = REGISTRY.register("mouthpiece", () -> new MouthpieceItem());
	public static final RegistryObject<Item> VAPE_POD_OF_WATER_BREATHING = REGISTRY.register("vape_pod_of_water_breathing", () -> new VapePodOfWaterBreathingItem());
}
